### ISSUE TITLE
refine function in util.R script

### ISSUE THREAD

**Issue by madhavitippani** [JianingYao/spaGCN_R#1]
Hello Jianing, 

Can you describe what are the inputs to the function 'refine' in the Util.R script. 

Thanks
Maddy

**Comment by JianingYao** [comment]
Hi Maddy, 

I have updated some explanations for the inputs to the "refine" function. Please let me know if there is any other question. 

Jianing

**Comment by madhavitippani** [comment]
Hi Jianing,

Thanks for the info, but how are these distances calculated? I am guessing it is in the calculate_adj.R script?
But I don't understand what input is given to each of the different distance metrics you are calculating in the calculate_adj.R. Like what actually from an `SPE` (spatial experiment object) will go into these functions. If you can provide more info on this it will be really helpful.
